# Backstage override configuration for your local development environment

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, Domain, System, API, Resource, Location]
  locations:
    - type: file
      target: ./catalog-avalia/all.yaml
      rules:
        - allow: [User, Group]
    - type: url
      target: https://github.com/AvaliaSystems/dx-hub/blob/main/dx-hub/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/AvaliaSystems/dx-hub-templates/blob/main/avalia.yaml
      rules:
        - allow: [Template]

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'
    local:
      publishDirectory: './techdocs-cache'
