---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: backstage.io
  annotations:
    github.com/project-slug: 'backstage/backstage'
    backstage.io/techdocs-ref: url:https://github.com/AvaliaSystems/backstage
spec:
  type: website
  lifecycle: production
  owner: cncf
