name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Node.js ${{ matrix.node-version }}
        working-directory: dx-hub
        run: yarn install --frozen-lockfile

      - name: Build type declarations
        working-directory: dx-hub
        run: yarn tsc

      - name: Build packages
        working-directory: dx-hub
        run: yarn build:all

      - name: Test
        working-directory: dx-hub
        run: yarn test:all

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        #        with:
        #          # This expects you to have a script called release which does a build for your packages and calls changeset publish
        #          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
